name: Fuzzer

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/fuzzer.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'
  pull_request:
    paths:
      - '.github/workflows/fuzzer.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'

jobs:
  Fuzzer:
    runs-on: ubuntu-latest
    container:
      image: swift:5.5
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/yaml/yaml-test-suite.git && cd yaml-test-suite && git checkout data && cd -
        name: 'Download fuzzer corpus'
      - run: swift build -c release -Xswiftc -sanitize=fuzzer -Xswiftc -parse-as-library
        name: 'Build fuzzer'
      - run: .build/release/yams-fuzzer yaml-test-suite -runs=10000000
        name: 'Run fuzzer'
