name: Fuzzer

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/fuzzer.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/fuzzer.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'

jobs:
  Linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.5
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/yaml/yaml-test-suite.git && cd yaml-test-suite && git checkout data && cd -
        name: 'Download fuzzer corpus'
      - run: swift build -c release -Xswiftc -sanitize=fuzzer -Xswiftc -parse-as-library
        name: 'Build fuzzer'
      - run: .build/release/yams-fuzzer yaml-test-suite &> /tmp/fuzzer.log &
        name: 'Run fuzzer'
      - run: sed '/#1048576/q' <(touch /tmp/fuzzer.log && tail -F /tmp/fuzzer.log)
        name: 'Check fuzzer made it to pulse #1048576'
      - run: cat /tmp/fuzzer.log
        if: ${{ failure() || cancelled() }}
        name: 'Print fuzzer logs'
